name: Select Option Workflow

on:
  workflow_dispatch:
    inputs:
      option:
        description: "Relase Type:"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
          - alpha
      text_input:
        description: "Enter message" # Describes the input
        required: true # Marks this input as required
        default: "Default message"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected option
        run: echo "Hello"
